name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        uses: cachix/install-nix-action@v13
            with:
              install_url: https://nixos-nix-install-tests.cachix.org/serve/i6laym9jw3wg9mw6ncyrk6gjx4l34vvx/install
              install_options: '--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve'
              extra_nix_config: |
                experimental-features = nix-command flakes
                access-tokens = github.com=${{ secrets.GITHUB_TOKEN }}
      - run: |
          nix build .#jonathanlorimerdev:exe:build-site
          result/bin/build-site

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build # The folder the action should deploy.
